name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches: [ main, master, tests, api_controller ]
  pull_request:
    branches: [ main, master, tests, api_controller ]
permissions:
  contents: write  # Нужно для деплоя в gh-pages
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install playwright-test-stats
        run: npm install -g playwright-test-stats

      - name: Set environment variables
        run: |
          echo "BOOKSTORE_BASE_URL=${{ secrets.BOOKSTORE_BASE_URL }}" >> $GITHUB_ENV
          echo "BOOKSTORE_CLIENT_LOGIN=${{ secrets.BOOKSTORE_CLIENT_LOGIN }}" >> $GITHUB_ENV
          echo "BOOKSTORE_CLIENT_PASSWORD=${{ secrets.BOOKSTORE_CLIENT_PASSWORD }}" >> $GITHUB_ENV
          echo "UI_TESTS_BASE_URL=${{ secrets.UI_TESTS_BASE_URL }}" >> $GITHUB_ENV

      # Переменная BASE URL не из env, а из secrets github
      - name: Set environment variables
        run: |
          echo "BOOKSTORE_BASE_URL=${{ secrets.BOOKSTORE_BASE_URL }}" >> $GITHUB_ENV
          echo "BOOKSTORE_CLIENT_LOGIN=${{ secrets.BOOKSTORE_CLIENT_LOGIN }}" >> $GITHUB_ENV
          echo "BOOKSTORE_CLIENT_PASSWORD=${{ secrets.BOOKSTORE_CLIENT_PASSWORD }}" >> $GITHUB_ENV
          echo "UI_TESTS_BASE_URL=${{ secrets.UI_TESTS_BASE_URL }}" >> $GITHUB_ENV
      - name: Run Playwright tests
        run: npx playwright test

        # сохраняем отчет pw
      - uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 20

      # сохраняем отчет allure
      - uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: allure-results
          path: allure-results
          retention-days: 20

      # забираем результаты предыдущего запуска отчета allure
      - uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

        # Формируем из allure-results отчет allure-report
      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history

      - name: Install allurectl
        run: |
            curl -o allurectl -L "https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64"
            chmod +x allurectl
            sudo mv allurectl /usr/local/bin/

      - name: Upload results to Allure TestOps
        if: always()
        run: |
          allurectl upload allure-results \
            --endpoint https://allure.autotests.cloud \
            --project-id 4729 \
            --token ${{ secrets.ALLURE_TOKEN }} \
            --launch-name "GitHub Run #${{ github.run_number }}"          publish_branch: gh-pages

      - name: Notify Telegram
        if: always()
        run: |
            STATUS=${{ job.status }}
            MESSAGE="🧪 *Playwright Tests завершены*%0A\
            Статус: *$STATUS*%0A\
            ✅ Пройдено: *$PASSED*%0A\
            ❌ Упало: *$FAILED*%0A\
            ⚠️ Пропущено: *$SKIPPED*%0A\
            📊 Всего: *$TOTAL*%0A\
              🔗 [Открыть Allure Report](https://a-chubarev.github.io/diplom_qaguru)"
              curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
              -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
              -d parse_mode=Markdown \
              -d text="$MESSAGE"