name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches: [ main, master, tests, api_controller ]
  pull_request:
    branches: [ main, master, tests, api_controller ]
permissions:
  contents: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install allurectl
        run: |
          curl -o allurectl -L "https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64"
          chmod +x allurectl
          sudo mv allurectl /usr/local/bin/

      # Переменные среды
      - name: Set environment variables
        run: |
          echo "BOOKSTORE_BASE_URL=${{ secrets.BOOKSTORE_BASE_URL }}" >> $GITHUB_ENV
          echo "BOOKSTORE_CLIENT_LOGIN=${{ secrets.BOOKSTORE_CLIENT_LOGIN }}" >> $GITHUB_ENV
          echo "BOOKSTORE_CLIENT_PASSWORD=${{ secrets.BOOKSTORE_CLIENT_PASSWORD }}" >> $GITHUB_ENV
          echo "UI_TESTS_BASE_URL=${{ secrets.UI_TESTS_BASE_URL }}" >> $GITHUB_ENV

      # Запуск тестов
      - name: Run Playwright tests
        run: npx playwright test

      - name: Get test stats from allure-results
        id: test_stats
        run: |
          # Считаем количество успешных, упавших и пропущенных тестов
          PASSED=$(find allure-results -type f -name "*.json" | xargs jq -r '.status' | grep passed | wc -l)
          FAILED=$(find allure-results -type f -name "*.json" | xargs jq -r '.status' | grep failed | wc -l)
          SKIPPED=$(find allure-results -type f -name "*.json" | xargs jq -r '.status' | grep skipped | wc -l)
          TOTAL=$((PASSED + FAILED + SKIPPED))
          
          echo "PASSED=$PASSED" >> $GITHUB_ENV
          echo "FAILED=$FAILED" >> $GITHUB_ENV
          echo "SKIPPED=$SKIPPED" >> $GITHUB_ENV
          echo "TOTAL=$TOTAL" >> $GITHUB_ENV

      # Сохраняем отчеты
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 20

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
          retention-days: 20

      - name: Checkout gh-pages for history
        if: always()
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: allure-results
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history

      - name: Upload results to Allure TestOps
        if: always()
        run: |
          allurectl upload allure-results/ \
            --endpoint https://allure.autotests.cloud \
            --project-id 4729 \
            --token ${{ secrets.ALLURE_TOKEN }} \
            --insecure \
            --launch-name "GitHub Run #${{ github.run_number }}"

      - name: Notify Telegram
        if: always()
        run: |
          STATUS=${{ job.status }}
          ALLURE_REPORT_URL=https://a-chubarev.github.io/diplom_qaguru
          MESSAGE="🧪 *Playwright Tests завершены*%0A\
          Статус: *$STATUS*%0A\
          ✅ Пройдено: *$PASSED*%0A\
          ❌ Упало: *$FAILED*%0A\
          ⚠️ Пропущено: *$SKIPPED*%0A\
          📊 Всего: *$TOTAL*%0A\
          🔗 [Открыть Allure Report]($ALLURE_REPORT_URL)"

          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d parse_mode=Markdown \
            -d text="$MESSAGE"